### ISSUE TITLE
CSS unimplemented

### ISSUE THREAD

**Issue by Prashant432142** [sagarnewpane/vroom#18]
When password reset page is loaded, the implementation of CSS is not co ordinated in the device trying to log in.

![reset pass](https://github.com/sagarnewpane/vroom/assets/119124486/c101db7b-f0d2-414f-a9b0-0ec971e6968f)

**Comment by sagarnewpane** [comment]
Fxied the css issue.
![Screenshot from 2024-04-18 08-44-56](https://github.com/sagarnewpane/vroom/assets/79533842/1591cac5-e79f-44d4-b213-5c5a1e6cfc79)

**Comment by sagarnewpane** [comment]
Issue fixed.
