### ISSUE TITLE
Improper notation of availability.

### ISSUE THREAD

**Issue by Prashant432142** [sagarnewpane/vroom#19]
The availability of cars should be represented by green color.

![available color](https://github.com/sagarnewpane/vroom/assets/119124486/0120036f-d6bb-4f87-bc1a-3c8b9ad0f7a6)

**Comment by ghost** [comment]
issue is fixed
![isuuefixed](https://github.com/sagarnewpane/vroom/assets/119931063/293d1a6d-4f06-4906-9876-887a0ecad877)
