### ISSUE TITLE
A car in maintenance can be booked. Booking option should be unavailable 

### ISSUE THREAD

**Issue by ghost** [sagarnewpane/vroom#21]
![image](https://github.com/sagarnewpane/vroom/assets/119931063/f06808cf-5b1e-4066-af4e-88548a17cc51)
![image](https://github.com/sagarnewpane/vroom/assets/119931063/8e4bfbac-46e4-4299-a69b-e7e737eeda49)

**Comment by sagarnewpane** [comment]
issue fixed.
![image](https://github.com/sagarnewpane/vroom/assets/79533842/d8cf8eec-ce67-4f2b-873a-26cf2f1abefd)
